### ISSUE TITLE
new numpy code error 

### ISSUE THREAD

**Issue by ebarberena2556** [robleseli/matplotlib-practice#2]
import numpy as np
variable = np.loadtxt(u"C:\\Users\\eduar\\OneDrive\\Desktop\\g823_2022175_1523.log",
                      delimiter= "$")

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    variable = np.loadtxt(u"C:\\Users\\eduar\\OneDrive\\Desktop\\g823_2022175_1523.log",
  File "C:\Users\eduar\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py", line 1301, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "C:\Users\eduar\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py", line 979, in _read
    arr = _load_from_filelike(
ValueError: could not convert string '' to float64 at row 0, column 1.

**Comment by ebarberena2556** [comment]
import numpy as np
variable = np.loadtxt(u"C:\\Users\\eduar\\OneDrive\\Desktop\\g823_2022175_1523.log", dtype = "str",
                      delimiter="$")
print(variable[:5])
[['' ' 29205.522,0286']
 ['' ' 29448.106,0229']
 ['' ' 28646.685,0281']
 ['' ' 28325.676,0247']
 ['' ' 28379.303,0286']]

new working code

**Comment by robleseli** [comment]
import numpy as np
variable = np.loadtxt(u"C:\Users\eduar\OneDrive\Desktop\g823_2022175_1523.log", dtype = "str",
delimiter="$")


print(variable[:5])
[['' ' 29205.522,0286']
['' ' 29448.106,0229']
['' ' 28646.685,0281']
['' ' 28325.676,0247']
['' ' 28379.303,0286']]
