### ISSUE TITLE
psuedocode for mag data plot

### ISSUE THREAD

**Issue by robleseli** [robleseli/matplotlib-practice#3]
import numpy as np
import matplotlib.pyplot as plt

 data = np.loadtxt(u"C:\Users\eduar\OneDrive\Desktop\g823_2022175_1523.log", dtype = "str",
# delimiter="$")
filename = 'g823_2022175_1523.log'

field_value_list = []
signal_value_list = []
for line in open(filename,'r'):
    split_line = line.split(',')
    field_value_str = split_line[0][2:]
    field_value = float(field_value_str)
    field_value_list.append(field_value)

    signal_value_str = split_line[1].replace('\n','')
    signal_value = int(signal_value_str)
    signal_value_list.append(signal_value)

field_value_array = np.array(field_value_list)
signal_value_array = np.array(signal_value_list)

count.field_value_array
 print results

#----------
#pseudocode

 #results / 10

 #round up to nearest 10

# store as x value

 #make sure field_value_array is stored as y values

 #plot this as scatter plot

 #-----------------

 #repeat process for signal value array
 

 #--------------------------

 #stack the two plots and label accordingly 

# x data is a numpy array of times, 10 points per second -- 0,0.1,0.2, etc...
# the same length as the two data arrays

# example plot:
plt.plot(field_value_array)
plt.savefig('field_value.png')

# x = data[:, 0]
# y = data[:, 1]

# #plot 1:
# x = np.array
# y = np.array(-------)
#
# plt.subplot(2,1,1)
# plt.plot(x,y)
# plt.title("-------")
#
#
# #plot 2:
# x = np.array(------)
# y = np.array(------)
#
# plt.subplot(2,1,2)
# plt.plot(x,y)
# plt.title("-------")
#
# plt.suptitle("Mag. Test Data")
# plt.show()

**Comment by robleseli** [comment]
working: full filepath opening

**Comment by ebarberena2556** [comment]
I was having problems finding the file on my local disk because the folder location was not showing up, so I uninstalled python and then reinstalled it but this time I did customization and changed the folder location to my desktop.
